name: Deploy Documentation

on:
  push:
    branches: [master]

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Pandoc and uv
        run: |
          sudo apt-get install pandoc
          curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Install model
        run: USE_CYTHON=1 uv sync --frozen --extra docs
      - name: Build documentation
        run: |
          cd doc
          make html
      - name: Deploy documentation to GitHub pages
        run: |
          cd doc/_build/html
          touch .nojekyll
          git config --global init.defaultBranch master
          git config --global user.name "CovertLab [bot]"
          git config --global user.email "CovertLab@users.noreply.github.com"
          git init
          git add -A
          git commit -m "Sphinx build from commit $GITHUB_SHA by GitHub Action"
          git push -f "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" master:gh-pages
