name: Test Documentation

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Pandoc and uv
        run: |
          sudo apt-get install pandoc
          curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Install model
        run: uv sync --extra docs
      - name: Build documentation
        run: |
          cd doc
          make html
