name: Deploy Documentation

on:
  push:
    branches: [deploy-docs]

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f doc/requirements.txt ]; then pip install -r doc/requirements.txt; fi
      - name: Build documentation
        run: |
          cd doc
          make html
      - name: Deploy documentation to GitHub pages
        run: |
          cd doc/_build/html
          touch .nojekyll
          git config --global init.defaultBranch master
          git config --global user.name "CovertLab [bot]"
          git config --global user.email "CovertLab@users.noreply.github.com"
          git init
          git add -A
          git commit -m "Sphinx build from commit $GITHUB_SHA by GitHub Action"
          git push -f "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" master:gh-pages
